### ISSUE TITLE
Nice to see some more nodes out there!

### ISSUE THREAD

**Issue by nolim1t** [runcitadel/compose#1]
Nice to see some more nodes out there. 

And would 100% support patches to this, and looking forward to seeing developments

However, are you should switching the MIT license is allowed like this. I see you took the work before Umbrel switched out for that non open source license. 

You are definetely allowed to switch it out before it went to MIT though.

**Comment by AaronDewes** [comment]
Yes, I'm sure changing the license like this I allowed from MIT, unlike GPL, it allows adding new restrictions, as long as I say that I forked it from Umbrel, which I do.

I opted for copyleft right now, so users get as much freedom as possible, without Umbrel being allowed to merge our code into Umbrel and sell it

**Comment by nolim1t** [comment]
Have you seen umbrel new license.. you can fork it now as long as you don't intend to sell it.

I think it's fair

**Comment by nolim1t** [comment]
Closing this. Keep things on track and focused
